apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/upcloud-load-balancer-config: |
      {
        "name": "my-wordpress-lb",
        "frontends": [
          {
            "name": "https",
            "mode": "http",
            "port": 443,
            "rules": [
              {
                "name": "add-ip-header",
                "priority": 100,
                "matchers": [],
                "actions": [
                  {
                    "type": "set_forwarded_headers",
                    "action_set_forwarded_headers": {}
                  }
                ]
              }
            ]
          },
          {
            "name": "http",
            "mode": "http",
            "port": 80,
            "rules": [
              {
                "name": "redirect-to-https",
                "priority": 100,
                "matchers": [],
                "actions": [
                  {
                    "type": "http_redirect",
                    "action_http_redirect": {
                      "scheme": "https"
                    }
                  }
                ]
              }
            ]
          }
        ]
      }
  name: wordpress
  labels:
    app: wordpress
spec:
  ports:
    - port: 443
      targetPort: 80
  selector:
    app: wordpress
  type: LoadBalancer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-nfs-pvc
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-nfs
  labels:
    app: wordpress-nfs
spec:
  selector:
    matchLabels:
      app: wordpress-nfs
  template:
    metadata:
      labels:
        app: wordpress-nfs
    spec:
      containers:
      - image: wordpress:6.2
        name: wordpress
        env:
        - name: WORDPRESS_DB_HOST
          valueFrom:
            secretKeyRef:
              name: mysql
              key: hostname
        - name: WORDPRESS_DB_NAME
          valueFrom:
            secretKeyRef:
              name: mysql
              key: database
        - name: WORDPRESS_DB_USER
          valueFrom:
            secretKeyRef:
              name: mysql
              key: user
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql
              key: password
        ports:
        - containerPort: 80
          name: wordpress
        volumeMounts:
        - name: wordpress-nfs-storage
          mountPath: /var/www/html
      volumes:
      - name: wordpress-nfs-storage
        persistentVolumeClaim:
          claimName: wp-nfs-pvc
