apiVersion: v1
kind: Service
metadata:
  name: wordpress-nfs
  labels:
    app: wordpress-nfs
spec:
  ports:
    - port: 80
  selector:
    app: wordpress-nfs
  type: LoadBalancer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-nfs-pvc
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-nfs
  labels:
    app: wordpress-nfs
spec:
  selector:
    matchLabels:
      app: wordpress-nfs
  template:
    metadata:
      labels:
        app: wordpress-nfs
    spec:
      containers:
      - image: wordpress:latest
        name: wordpress
        env:
        - name: WORDPRESS_DB_HOST
          valueFrom:
            secretKeyRef:
              name: mysql
              key: hostname
        - name: WORDPRESS_DB_NAME
          valueFrom:
            secretKeyRef:
              name: mysql
              key: database
        - name: WORDPRESS_DB_USER
          valueFrom:
            secretKeyRef:
              name: mysql
              key: user
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql
              key: password
        ports:
        - containerPort: 80
          name: wordpress
        volumeMounts:
        - name: wordpress-nfs-storage
          mountPath: /var/www/html
      volumes:
      - name: wordpress-nfs-storage
        persistentVolumeClaim:
          claimName: wp-nfs-pvc